# Generated by Django 5.2.14 on 2026-05-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BentoShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('description', models.TextField(blank=True, verbose_name='店舗説明')),
                ('business_status', models.CharField(choices=[('open', '営業中'), ('closed', '本日休み'), ('preparing', '準備中')], default='closed', max_length=20, verbose_name='営業状況')),
                ('stock_status', models.CharField(choices=[('enough', '十分あり'), ('low', '残り少ない'), ('sold_out', '売り切れ')], default='enough', max_length=20, verbose_name='在庫状況')),
                ('today_menu', models.TextField(blank=True, verbose_name='今日のメニュー')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
