# Generated by Django 5.2.14 on 2026-05-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shopstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bentoshop',
            name='discount_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了予定時刻'),
        ),
        migrations.AddField(
            model_name='bentoshop',
            name='discount_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='残り個数'),
        ),
        migrations.AddField(
            model_name='bentoshop',
            name='discount_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='値下げ内容'),
        ),
        migrations.AddField(
            model_name='bentoshop',
            name='is_discount_active',
            field=models.BooleanField(default=False, verbose_name='値下げ中'),
        ),
    ]
